### PR TITLE
Statemanager

### PR DESCRIPTION
**Pull request by Quaker762**
These are a few classes (as well as the base class, `sh3_scene`) to demonstrate how I think we should handle scenes. Most of how it'll probably work is in `scene.hpp`, but basically where the actual game is initialised has a pointer that controls which state is currently 'active' (i.e being drawn, updated etc). With this style of framework, in some kind of "transition" function, we can add effects like fading in etc.

### CODE REVIEW

**Comment by Quaker762** [comment]
Shit, looks like it's added my previous commits in this one.... It would seem git hates me lol.

**Comment by z33ky** [comment]
You should have branched off this master's commit. Locally I have done this: `git remote add upstream git@github.com:Palm-Studios/sh3redux.git` and I do `git fetch --all --prune` from time to time. Then you can `git checkout -b new-branch upstream/master` to branch from that.
Edit: To redo it you can `git branch --move statemanager statemanager-old && git checkout -b statemanager upstream/master && git cherry-pick statemanager-old && git branch -D statemanager-old`.

**Comment by z33ky** [comment]
We could have a `UpdateBackground` method that is called on the inactive scenes on the scene stack if sound is not supposed to be a global thing.
A `DrawBackground` method would allow us things like (partially) transparent background for the inventory screen. The 3D-scene could do gray-scaling or blurring or whatever to indicate that it is paused.

Overwritten virtual methods should use the C++11 `override` specifier.

As a side-note, I have an input-system built on top of SDL somewhere, I'll dig it up and see what state it's in.

**Comment by Quaker762** [comment]
> We could have a UpdateBackground method that is called on the inactive scenes on the scene stack if sound is not supposed to be a global thing.

Sounds good. Would this need to be threaded? Or should it just constantly run independent of what scene is currently active?

> A DrawBackground method would allow us things like (partially) transparent background for the inventory screen. The 3D-scene could do gray-scaling or blurring or whatever to indicate that it is paused.

I like the sound of the transparency, but the SILENT HILL inventory is WAY more simple (I'm not sure whether you've played or not, so please forgive me if you have). The hardest thing to implement, IMHO, will be the effects like having a small view of the 3D scene as the status.. An example of this is [here](http://www.mobygames.com/images/shots/l/741357-silent-hill-hd-collection-playstation-3-screenshot-silent.jpg) and [here](https://youtu.be/Z4wERZf6bns?t=20m23s)

One thing I've noticed is that every part of the inventory is in sync; the status colour and selection pulse together after some arbitrary time.

**Comment by z33ky** [comment]
> Or should it just constantly run independent of what scene is currently active?

That.
Threading should probably happen on another level than per-scene.
While I know how to use synchronization mechanisms like locks, condition variables, atomics an such I don't really have experience with multi-threading beyond producer-consumer based approaches or embarrassingly parallelizable algorithms.

> I'm not sure whether you've played or not, so please forgive me if you have

I have not. It was on my "if I ever get around to it" list, but I've never really thought about it since I switched to running solely Linux on my computers.
I actually don't know very much about the game at all beyond some screenshots and a little bit of gameplay footage used in some videos I saw, but I'm hopeful this project will drive me to get to know the series :)

> The hardest thing to implement, IMHO, will be the effects like having a small view of the 3D scene as the status.

Unfortunately my experience with 3D programming is very basic. I used to do a little bit of immediate mode stuff, I did a spinning, colored, bumpmapped cube with OpenGL 3 using some internet tutorial and I used a tiny bit of (OGRE3D)[http://www.ogre3d.org/], less than a full tutorial worth.
For that effect though, aren't framebuffer objects still a thing in modern OpenGL?

**Comment by Quaker762** [comment]
> Threading should probably happen on another level than per-scene.
While I know how to use synchronization mechanisms like locks, condition variables, atomics an such I don't really have experience with multi-threading beyond producer-consumer based approaches or embarrassingly parallelizable algorithms.

Same here. I'm under the impression that threading in a game engine, for the most part, is a big no-no anyway.

> I have not. It was on my "if I ever get around to it" list, but I've never really thought about it since I switched to running solely Linux on my computers.

Haha no worries. If you have a beefy enough gpu/cpu, you could probably dick around with the PS2 version on PCSX2, they're the same for the most part (until this gets to a playable level hehe)

> I actually don't know very much about the game at all beyond some screenshots and a little bit of gameplay footage used in some videos I saw, but I'm hopeful this project will drive me to get to know the series :)

It's one of the best survival-horror games ever. They're pretty enjoyable to play, especially at 2 in the morning with the lights off HAHA.

> Unfortunately my experience with 3D programming is very basic

Same here. I was going to treat this as my learning project for the most part until it got shared on reddit... For the most part, Mike has done most of the work, it's going to mainly be a whole lot of game logic as well as converting his fixed pipeline calls over to more modern shaders etc.

> For that effect though, aren't framebuffer objects still a thing in modern OpenGL?

From the little GL I remember, I believe people do still use them. I guess the status could just be the 3D Scene dumped to an FBO, scaled down and then drawn.

EDIT: Looks like this is the way to go, actually, according to [wikipedia](https://en.wikipedia.org/wiki/Framebuffer_object)

> Can be used to create views of other scenes, for example: a TV in a house showing the view from a secondary camera. A scene can be rendered through an FBO to a texture, then that texture can be applied to the surface of a TV. This is sometimes called "Render to Texture" or RTT.

**Comment by z33ky** [comment]
> I'm under the impression that threading in a game engine, for the most part, is a big no-no anyway.

Desktops and consoles have multi-core CPUs, so I'd think game developers do want to leverage the available resources. Some skimming of the internet on multi-threading for game-engines suggest that a job-system (aka task-system) is the way to go. I'm not sure about synchronization, but (this)[https://software.intel.com/en-us/articles/designing-the-framework-of-a-parallel-game-engine] suggests a form of message-passing to do data mutation.

> It's one of the best survival-horror games ever. They're pretty enjoyable to play, especially at 2 in the morning with the lights off HAHA.

I'll keep my teddy bear near for support :S

> Same here. I was going to treat this as my learning project for the most part until it got shared on reddit...

Hehe, that's one of the reasons why I manage a private git server ^.^
It might be sensible to rely on a framework. I remember wanting to try out (OpenSceneGraph)[http://www.openscenegraph.org], but I can't really make an informed suggestion here.

**Comment by Quaker762** [comment]
> Desktops and consoles have multi-core CPUs, so I'd think game developers do want to leverage the available resources. Some skimming of the internet on multi-threading for game-engines suggest that a job-system (aka task-system) is the way to go.

Ahh okay. I read a few articles that spoke against using threading, however they may have been old.

> I'll keep my teddy bear near for support :S

Best way to deal with it.

> It might be sensible to rely on a framework. I remember wanting to try out (OpenSceneGraph)[http://www.openscenegraph.org], but I can't really make an informed suggestion here.

I don't really like depending on frameworks, as I feel it takes away a bit of the control you have (hence my stdtype, util etc). I'm still a bit sketchy using GLM (but included it anyway) because we can probably just make a whole lot of `structs` for the datatypes we need (like `vertex` etc)

**Comment by z33ky** [comment]
> I don't really like depending on frameworks, as I feel it takes away a bit of the control you have

True. Personally I give up control where I don't feel competent or knowledgeable enough and don't want to invest the time beforehand to obtain sufficient knowledge on the subject. Obtaining knowledge is tricky, since you don't always know what else there is to know, or which techniques have been superseded with better ones. I'm always happy when I know competent people that I can ask; For graphics programming no one comes to mind though.
You did state that you wanted to treat this as a learning project, so it really makes sense that you want to avoid using frameworks and build it yourself. You can still use the available frameworks and peek inside to learn from them, thanks to open source software.

Also, this discussion is getting off topic...

**Comment by Quaker762** [comment]
Deprecated. We'll have some new ideas for this in the future when we get some more engine stuff done/refactored, first

**Pull request closed without merging**
