### PR TITLE
Properly add CMake library include paths

### PR DESCRIPTION
**Pull request by z33ky**
This might fix the problem @Quaker762 had with CMake.

Also, make sure you select "rebase and merge" on this pull request :)

### CODE REVIEW

**Comment by z33ky** [comment]
Did this fix it for you or do you still get errors?

**Comment by CSymes** [comment]
Dunno about Jesse, but I'm still getting the GLM versioning issues.

<details><summary>CMake results, though I assume you've already seen these</summary>

    -- The CXX compiler identification is GNU 6.3.1
    -- Check for working CXX compiler: /usr/lib/hardening-wrapper/bin/c++
    -- Check for working CXX compiler: /usr/lib/hardening-wrapper/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Performing Test HAVE_fcolor-diagnostics_FLAG
    -- Performing Test HAVE_fcolor-diagnostics_FLAG - Failed
    -- Performing Test HAVE_fdiagnostics-color=always_FLAG
    -- Performing Test HAVE_fdiagnostics-color=always_FLAG - Success
    -- Forcing colored compiler output
    -- Performing Test HAVE_Weverything_FLAG
    -- Performing Test HAVE_Weverything_FLAG - Failed
    -- Performing Test HAVE_Wcxx98-compat_FLAG
    -- Performing Test HAVE_Wcxx98-compat_FLAG - Failed
    -- Performing Test HAVE_Wcxx98-compat-pedantic_FLAG
    -- Performing Test HAVE_Wcxx98-compat-pedantic_FLAG - Failed
    -- Performing Test HAVE_Wexit-time-destructors_FLAG
    -- Performing Test HAVE_Wexit-time-destructors_FLAG - Failed
    -- Performing Test HAVE_Wignored-qualifiers_FLAG
    -- Performing Test HAVE_Wignored-qualifiers_FLAG - Success
    -- Disabling -Wignored-qualifiers
    -- Performing Test HAVE_Wpadded_FLAG
    -- Performing Test HAVE_Wpadded_FLAG - Success
    -- Disabling -Wpadded
    -- Found GLEW: /usr/include  
    CMake Error at source/CMakeLists.txt:4 (find_package):
      Could not find a configuration file for package "glm" that is compatible
      with requested version "".

      The following configuration files were considered but not accepted:

        /usr/lib64/cmake/glm/glmConfig.cmake, version: 0.9.8 (32bit)
        /usr/lib/cmake/glm/glmConfig.cmake, version: 0.9.8 (32bit)
        /lib64/cmake/glm/glmConfig.cmake, version: 0.9.8 (32bit)
        /lib/cmake/glm/glmConfig.cmake, version: 0.9.8 (32bit)



    -- Configuring incomplete, errors occurred!
    See also "sh3redux/build/CMakeFiles/CMakeOutput.log".
    See also "sh3redux/build/CMakeFiles/CMakeError.log".

</details>

**Comment by z33ky** [comment]
> though I assume you've already seen these

It could be an error with your glm installation (I know Arch's package has [one](https://bugs.archlinux.org/task/52501), which can be fixed by manually editing the `CMAKE_SIZEOF_VOID_P` check in `/usr/lib/cmake/glm/glmConfig.cmake`) or you indeed have installed a 32-bit glm library, but are trying to build for 64-bit, which can be changed via `CFLAGS=-m32 CXXFLAGS=-m32`.

**Comment by Quaker762** [comment]
Sorry I was a bit busy today. I'm still getting the error on Arch.. I'll try twiddling with `glmConfig.cmake`. According to the glm bug tracker, this was 'fixed', but I honestly doubt it.

**Comment by z33ky** [comment]
Err it's `/usr/lib/cmake/glm/glmConfigVersion.cmake` that needs to be modified.

> According to the glm bug tracker, this was 'fixed',

Well, the Arch ticket has the status "reopened", so it probably was - for a while:

> Since a recent update, the exact same problem came back

**Pull request merged**
