### PR TITLE
Basic Texture loading

### PR DESCRIPTION
**Pull request by Quaker762**
Basic texture loading implemented. Currently stores a reference to sh3_arc in the actual texture class, so this probably needs a refactor (when I think of a better way)

### CODE REVIEW

**Comment by z33ky** [comment]
Can you squash those two commits? If you don't know how to do that there should be guides on the Internet.

You're using Doxygen-style comments now, so should we switch?
There are some differences in how you use them, some will result in incorrectly extracted documentation. We should probably land a change that introduces the `Doxyfile` first so the generated documentation can be checked.

**Comment by Quaker762** [comment]
I'm not too sure how to squash now that they've been merged. Do I have to revert changes, squash and the n recommit?

Also yes, definitely change to the Doxygen style. Make any changes that you need, I used the Doxygen reference as a guide but only have basic knowledge on how it works. I also have a logo to use for the documentation, so I can include that in a PR.

**Comment by z33ky** [comment]
You can be naughty and reset the history via `git reset --hard e59cb18239e191b8a40c0784cec9e2a1ccb94d63 && git push --force-with-lease`.
I'll just redo my previous pull request as well.

If you want I can review your changes if you don't merge your pull requests directly. Otherwise you could just directly push onto Palm-Studios:master.
Btw if you want to avoid the merge-commits in the history you can enable rebasing of pull requests in the project settings.

**Comment by Quaker762** [comment]
Am I resetting my fork or this repo exactly (sorry I'm terrible at resolving repo conflicts like this and it's 2:15AM hahahaha). 

Sounds good, I'll enable that.

**Comment by z33ky** [comment]
This one. The `push --force-with-lease` should go to this repository to essentially make it as if the last few pull requests never happened.
In case you're missing anything you can always go back to a previous state via `git reflog`.

**Comment by Quaker762** [comment]
Okay done. Time to redo this stuff now. Should I do all texturing in one PR, merge, and then do comment updating in another?

**Comment by z33ky** [comment]
Yeah, it's easier to review individual changes.

**Pull request merged**
